package com.buildgraph.prototype.agent;

import com.buildgraph.prototype.common.MockData;
import java.util.List;
import java.util.Map;
import org.springframework.web.server.ResponseStatusException;

public class LlmAgentRunner implements AgentRunner {
    private static final String SYSTEM_PROMPT = """
            당신은 BuildGraph AI의 하드웨어 컨설팅 Agent입니다.
            입력된 Agent 목적, RAG 근거, Tool 검증 결과만 사용해 한국어 summary를 작성하십시오.
            확인되지 않은 부품명, 가격, 성능 수치를 새로 지어내지 마십시오.
            사용자가 바로 이해할 수 있게 핵심 판단, 주의점, 다음 행동을 3~5문장으로 답하십시오.
            """;

    private final AgentTraceService agentTraceService;
    private final OpenAiResponsesClient openAiResponsesClient;

    public LlmAgentRunner(AgentTraceService agentTraceService, OpenAiResponsesClient openAiResponsesClient) {
        this.agentTraceService = agentTraceService;
        this.openAiResponsesClient = openAiResponsesClient;
    }

    @Override
    public void run(String sessionId, AgentSessionRoot root, AgentRunProfile profile) {
        AgentRagEvidenceDraft evidence = AgentRunTraceDrafts.ragEvidence(root, profile);
        String evidenceId = agentTraceService.recordRagEvidence(sessionId, evidence);
        agentTraceService.advanceStatus(sessionId, AgentStatus.RAG_SEARCHED, "SYSTEM", "RAG evidence retrieved for " + profile.purpose());

        List<AgentToolInvocationDraft> toolDrafts = AgentRunTraceDrafts.toolInvocations(root, profile);
        List<String> toolInvocationIds = toolDrafts.stream()
                .map(draft -> agentTraceService.recordToolInvocation(sessionId, draft))
                .toList();
        agentTraceService.advanceStatus(sessionId, AgentStatus.TOOLS_CALLED, "SYSTEM", "tool invocations completed for " + profile.purpose());

        try {
            String summary = openAiResponsesClient.createSummary(
                    SYSTEM_PROMPT,
                    userPrompt(root, profile, evidenceId, evidence, toolInvocationIds, toolDrafts)
            );
            agentTraceService.updateSummary(sessionId, summary);
            agentTraceService.advanceStatus(sessionId, AgentStatus.SUMMARY_READY, "SYSTEM", "LLM summary generated by " + openAiResponsesClient.model());
            agentTraceService.advanceStatus(sessionId, AgentStatus.SUCCEEDED, "SYSTEM", "LLM agent run completed");
        } catch (RuntimeException error) {
            agentTraceService.updateSummary(sessionId, "LLM summary generation failed: " + safeReason(error));
            agentTraceService.advanceStatus(sessionId, AgentStatus.FALLBACK_READY, "SYSTEM", "LLM summary generation failed");
            agentTraceService.advanceStatus(sessionId, AgentStatus.FAILED, "SYSTEM", "LLM agent run failed");
        }
    }

    private static String userPrompt(
            AgentSessionRoot root,
            AgentRunProfile profile,
            String evidenceId,
            AgentRagEvidenceDraft evidence,
            List<String> toolInvocationIds,
            List<AgentToolInvocationDraft> toolDrafts
    ) {
        return AgentTraceService.json(MockData.map(
                "purpose", profile.purpose().name(),
                "summaryTarget", profile.summaryTarget(),
                "root", MockData.map(
                        "type", root.type().name(),
                        "id", root.publicId()
                ),
                "ragEvidence", MockData.map(
                        "id", evidenceId,
                        "sourceId", evidence.sourceId(),
                        "summary", evidence.summary(),
                        "chunkText", evidence.chunkText(),
                        "score", evidence.score(),
                        "metadata", evidence.metadata()
                ),
                "toolInvocations", toolItems(toolInvocationIds, toolDrafts),
                "outputInstruction", "Return only the customer-facing Korean summary text."
        ));
    }

    private static List<Map<String, Object>> toolItems(List<String> ids, List<AgentToolInvocationDraft> drafts) {
        return java.util.stream.IntStream.range(0, drafts.size())
                .mapToObj(index -> {
                    AgentToolInvocationDraft draft = drafts.get(index);
                    return MockData.map(
                            "id", ids.get(index),
                            "toolName", draft.toolName(),
                            "status", draft.status().name(),
                            "confidence", draft.confidence().name(),
                            "summary", draft.summary(),
                            "requestPayload", draft.requestPayload(),
                            "resultPayload", draft.resultPayload()
                    );
                })
                .toList();
    }

    private static String safeReason(RuntimeException error) {
        if (error instanceof ResponseStatusException responseStatusException && responseStatusException.getReason() != null) {
            return responseStatusException.getReason();
        }
        String message = error.getMessage();
        return message == null || message.isBlank() ? error.getClass().getSimpleName() : message;
    }
}
