package com.buildgraph.prototype.ticket.contract;

public enum SupportReasonCode {
    AGENT_REGISTRATION_ERROR,
    AGENT_UPLOAD_ERROR,
    DRIVER_ERROR_REPEAT,
    WINDOWS_UPDATE_FAILURE,
    APP_CRASH,
    RUNTIME_MISSING,
    STORAGE_LOW,
    MEMORY_PRESSURE,
    STARTUP_LOAD,
    SERVICE_CRASH_LOOP,
    DNS_FAILURE,
    ADAPTER_DISABLED,
    BOOT_REMOTE_BLOCKED,
    SMART_CRITICAL,
    DISK_IO_ERROR_REPEAT,
    WHEA_ERROR_REPEAT,
    BSOD_REPEAT,
    KERNEL_POWER_REPEAT,
    THERMAL_SHUTDOWN,
    FAN_RPM_ZERO,
    UNSUPPORTED_SCOPE,
    INSUFFICIENT_EVIDENCE
}
