package com.buildgraph.prototype.ticket.contract;

public enum VisitReason {
    BOOT_UNAVAILABLE,
    REMOTE_CONNECTION_UNAVAILABLE,
    QUICK_ASSIST_UNAVAILABLE,
    SMART_CRITICAL,
    BAD_BLOCK,
    DISK_IO_ERROR_REPEAT,
    WHEA_HARDWARE_ERROR,
    BSOD_REPEAT,
    KERNEL_POWER_REPEAT,
    POWER_SHUTDOWN_UNDER_LOAD,
    FAN_NOT_WORKING,
    THERMAL_SHUTDOWN,
    HARDWARE_DEVICE_NOT_DETECTED
}
