CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255),
  name VARCHAR(100) NOT NULL,
  role VARCHAR(30) NOT NULL,
  terms_accepted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  marketing_accepted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users(deleted_at);

CREATE TABLE IF NOT EXISTS user_auth_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  provider VARCHAR(50) NOT NULL,
  provider_user_id VARCHAR(255) NOT NULL,
  provider_email VARCHAR(255) NOT NULL,
  email_verified BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_user_id)
);

CREATE INDEX IF NOT EXISTS idx_user_auth_providers_user_id ON user_auth_providers(user_id);
CREATE INDEX IF NOT EXISTS idx_user_auth_providers_provider_email ON user_auth_providers(provider_email);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  token_hash VARCHAR(255) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

CREATE TABLE IF NOT EXISTS parts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  category VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  manufacturer VARCHAR(100),
  price INTEGER NOT NULL,
  status VARCHAR(30) NOT NULL,
  attributes JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_parts_category ON parts(category);
CREATE INDEX IF NOT EXISTS idx_parts_status ON parts(status);
CREATE INDEX IF NOT EXISTS idx_parts_name ON parts(name);
CREATE INDEX IF NOT EXISTS idx_parts_deleted_at ON parts(deleted_at);

CREATE TABLE IF NOT EXISTS price_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id BIGINT NOT NULL REFERENCES parts(id),
  price INTEGER NOT NULL,
  source VARCHAR(100) NOT NULL,
  collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  raw_payload JSONB
);

CREATE INDEX IF NOT EXISTS idx_price_snapshots_part_id ON price_snapshots(part_id);
CREATE INDEX IF NOT EXISTS idx_price_snapshots_part_collected ON price_snapshots(part_id, collected_at);

CREATE TABLE IF NOT EXISTS price_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  part_id BIGINT NOT NULL REFERENCES parts(id),
  target_price INTEGER NOT NULL,
  status VARCHAR(30) NOT NULL,
  triggered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_price_alerts_user_status ON price_alerts(user_id, status);
CREATE INDEX IF NOT EXISTS idx_price_alerts_part_target ON price_alerts(part_id, target_price);
CREATE INDEX IF NOT EXISTS idx_price_alerts_deleted_at ON price_alerts(deleted_at);

CREATE TABLE IF NOT EXISTS price_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  requested_by BIGINT NOT NULL REFERENCES users(id),
  status VARCHAR(30) NOT NULL,
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  error_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_price_jobs_status ON price_jobs(status);
CREATE INDEX IF NOT EXISTS idx_price_jobs_created_at ON price_jobs(created_at);

CREATE TABLE IF NOT EXISTS compatibility_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_key VARCHAR(120) NOT NULL UNIQUE,
  category VARCHAR(50) NOT NULL,
  "condition" JSONB NOT NULL,
  result_status VARCHAR(30) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_compatibility_rules_category ON compatibility_rules(category);
CREATE INDEX IF NOT EXISTS idx_compatibility_rules_deleted_at ON compatibility_rules(deleted_at);

CREATE TABLE IF NOT EXISTS benchmark_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id BIGINT REFERENCES parts(id),
  benchmark_key VARCHAR(120) NOT NULL UNIQUE,
  summary TEXT NOT NULL,
  score NUMERIC(10, 2),
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_benchmark_summaries_part_id ON benchmark_summaries(part_id);
CREATE INDEX IF NOT EXISTS idx_benchmark_summaries_deleted_at ON benchmark_summaries(deleted_at);

CREATE TABLE IF NOT EXISTS requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  raw_message TEXT NOT NULL,
  budget INTEGER,
  usage_tags TEXT[],
  parsed_context JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_requirements_user_id ON requirements(user_id);
CREATE INDEX IF NOT EXISTS idx_requirements_created_at ON requirements(created_at);

CREATE TABLE IF NOT EXISTS builds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  requirement_id BIGINT NOT NULL REFERENCES requirements(id),
  name VARCHAR(120) NOT NULL,
  total_price INTEGER NOT NULL,
  confidence VARCHAR(30) NOT NULL,
  warnings JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_builds_requirement_id ON builds(requirement_id);
CREATE INDEX IF NOT EXISTS idx_builds_created_at ON builds(created_at);

CREATE TABLE IF NOT EXISTS build_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  build_id BIGINT NOT NULL REFERENCES builds(id),
  part_id BIGINT NOT NULL REFERENCES parts(id),
  category VARCHAR(50) NOT NULL,
  price INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (build_id, category)
);

CREATE INDEX IF NOT EXISTS idx_build_items_build_id ON build_items(build_id);
CREATE INDEX IF NOT EXISTS idx_build_items_part_id ON build_items(part_id);

CREATE TABLE IF NOT EXISTS agent_log_uploads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  range_minutes INTEGER NOT NULL,
  status VARCHAR(30) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_size BIGINT,
  storage_path TEXT,
  summary TEXT,
  consent_accepted_at TIMESTAMPTZ NOT NULL,
  delete_after TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_log_uploads_user_id ON agent_log_uploads(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_log_uploads_status ON agent_log_uploads(status);
CREATE INDEX IF NOT EXISTS idx_agent_log_uploads_delete_after ON agent_log_uploads(delete_after);
CREATE INDEX IF NOT EXISTS idx_agent_log_uploads_created_at ON agent_log_uploads(created_at);

CREATE TABLE IF NOT EXISTS as_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  log_upload_id BIGINT REFERENCES agent_log_uploads(id),
  assigned_admin_id BIGINT REFERENCES users(id),
  symptom TEXT NOT NULL,
  status VARCHAR(30) NOT NULL,
  cause_candidates JSONB,
  upgrade_candidates JSONB,
  admin_note TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_as_tickets_user_id ON as_tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_as_tickets_log_upload_id ON as_tickets(log_upload_id);
CREATE INDEX IF NOT EXISTS idx_as_tickets_status ON as_tickets(status);
CREATE INDEX IF NOT EXISTS idx_as_tickets_assigned_admin_id ON as_tickets(assigned_admin_id);
CREATE INDEX IF NOT EXISTS idx_as_tickets_created_at ON as_tickets(created_at);
CREATE INDEX IF NOT EXISTS idx_as_tickets_deleted_at ON as_tickets(deleted_at);

CREATE TABLE IF NOT EXISTS agent_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  requirement_id BIGINT REFERENCES requirements(id),
  build_id BIGINT REFERENCES builds(id),
  as_ticket_id BIGINT REFERENCES as_tickets(id),
  status VARCHAR(30) NOT NULL,
  summary TEXT,
  state_timeline JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_agent_sessions_user_id ON agent_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status ON agent_sessions(status);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_requirement_id ON agent_sessions(requirement_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_build_id ON agent_sessions(build_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_as_ticket_id ON agent_sessions(as_ticket_id);

CREATE TABLE IF NOT EXISTS tool_invocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  agent_session_id BIGINT NOT NULL REFERENCES agent_sessions(id),
  tool_name VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL,
  confidence VARCHAR(30) NOT NULL,
  summary TEXT NOT NULL,
  request_payload JSONB,
  result_payload JSONB,
  latency_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tool_invocations_agent_session_id ON tool_invocations(agent_session_id);
CREATE INDEX IF NOT EXISTS idx_tool_invocations_tool_status ON tool_invocations(tool_name, status);
CREATE INDEX IF NOT EXISTS idx_tool_invocations_created_at ON tool_invocations(created_at);

CREATE TABLE IF NOT EXISTS rag_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  agent_session_id BIGINT REFERENCES agent_sessions(id),
  source_id VARCHAR(120) NOT NULL,
  chunk_text TEXT NOT NULL,
  summary TEXT NOT NULL,
  score NUMERIC(8, 5),
  embedding vector(1536),
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rag_evidence_agent_session_id ON rag_evidence(agent_session_id);
CREATE INDEX IF NOT EXISTS idx_rag_evidence_source_id ON rag_evidence(source_id);
CREATE INDEX IF NOT EXISTS idx_rag_evidence_score ON rag_evidence(score);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT NOT NULL REFERENCES users(id),
  action VARCHAR(100) NOT NULL,
  target_type VARCHAR(100) NOT NULL,
  target_id VARCHAR(120),
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_actor_user_id ON admin_audit_logs(actor_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target ON admin_audit_logs(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created_at ON admin_audit_logs(created_at);
