CREATE TABLE quote_draft_history_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  quote_draft_id BIGINT NOT NULL REFERENCES quote_drafts(id) ON DELETE CASCADE,
  change_group_id UUID NOT NULL,
  action_type VARCHAR(40) NOT NULL,
  action_label VARCHAR(160) NOT NULL,
  related_categories JSONB NOT NULL DEFAULT '[]'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  snapshot_payload JSONB NOT NULL,
  snapshot_fingerprint VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '30 days'),
  CONSTRAINT chk_quote_draft_history_action CHECK (action_type IN (
    'ITEM_ADD',
    'ITEM_REPLACE',
    'ITEM_REMOVE',
    'QUANTITY_CHANGE',
    'AI_BUILD_APPLY',
    'RESTORE'
  ))
);

CREATE UNIQUE INDEX ux_quote_draft_history_change_group
  ON quote_draft_history_entries(quote_draft_id, change_group_id);

CREATE INDEX idx_quote_draft_history_recent
  ON quote_draft_history_entries(quote_draft_id, created_at DESC, id DESC);

CREATE INDEX idx_quote_draft_history_expiry
  ON quote_draft_history_entries(expires_at);
