CREATE TABLE as_chat_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  as_ticket_id BIGINT NOT NULL REFERENCES as_tickets(id),
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  title VARCHAR(160) NOT NULL DEFAULT 'AS AI 챗봇 상담',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_as_chat_sessions_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE UNIQUE INDEX ux_as_chat_sessions_active_ticket_user
  ON as_chat_sessions(user_id, as_ticket_id)
  WHERE status = 'ACTIVE' AND deleted_at IS NULL;

CREATE INDEX idx_as_chat_sessions_user_id ON as_chat_sessions(user_id);
CREATE INDEX idx_as_chat_sessions_as_ticket_id ON as_chat_sessions(as_ticket_id);
CREATE INDEX idx_as_chat_sessions_deleted_at ON as_chat_sessions(deleted_at);

CREATE TABLE as_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  chat_session_id BIGINT NOT NULL REFERENCES as_chat_sessions(id),
  role VARCHAR(30) NOT NULL,
  content TEXT NOT NULL,
  structured_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  agent_session_id BIGINT REFERENCES agent_sessions(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_as_chat_messages_role CHECK (role IN ('USER', 'ASSISTANT'))
);

CREATE INDEX idx_as_chat_messages_session_id ON as_chat_messages(chat_session_id);
CREATE INDEX idx_as_chat_messages_agent_session_id ON as_chat_messages(agent_session_id);
CREATE INDEX idx_as_chat_messages_created_at ON as_chat_messages(created_at);
