CREATE TABLE recommendation_training_datasets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  name VARCHAR(160) NOT NULL,
  source_surface VARCHAR(80) NOT NULL DEFAULT 'HOME_PARTS',
  filters JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  eligible_count INTEGER NOT NULL DEFAULT 0,
  included_count INTEGER NOT NULL DEFAULT 0,
  excluded_count INTEGER NOT NULL DEFAULT 0,
  created_by BIGINT REFERENCES users(id),
  locked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_recommendation_training_datasets_status CHECK (status IN ('DRAFT', 'LOCKED', 'TRAINED', 'ARCHIVED'))
);

CREATE INDEX idx_recommendation_training_datasets_status ON recommendation_training_datasets(status);
CREATE INDEX idx_recommendation_training_datasets_created_at ON recommendation_training_datasets(created_at);
CREATE INDEX idx_recommendation_training_datasets_deleted_at ON recommendation_training_datasets(deleted_at);

CREATE TABLE recommendation_training_dataset_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  dataset_id BIGINT NOT NULL REFERENCES recommendation_training_datasets(id),
  event_id BIGINT NOT NULL REFERENCES recommendation_events(id),
  included BOOLEAN NOT NULL DEFAULT true,
  excluded_reason VARCHAR(240),
  label_score_snapshot NUMERIC(6, 2) NOT NULL,
  features_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  event_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_recommendation_training_dataset_items_event UNIQUE (dataset_id, event_id)
);

CREATE INDEX idx_recommendation_training_dataset_items_dataset ON recommendation_training_dataset_items(dataset_id);
CREATE INDEX idx_recommendation_training_dataset_items_event ON recommendation_training_dataset_items(event_id);
CREATE INDEX idx_recommendation_training_dataset_items_included ON recommendation_training_dataset_items(dataset_id, included);

CREATE TABLE recommendation_training_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  dataset_id BIGINT NOT NULL REFERENCES recommendation_training_datasets(id),
  model_version_id BIGINT REFERENCES recommendation_model_versions(id),
  status VARCHAR(40) NOT NULL DEFAULT 'QUEUED',
  worker_id VARCHAR(120),
  model_version VARCHAR(120),
  artifact_path TEXT,
  metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  log_summary TEXT,
  queued_by BIGINT REFERENCES users(id),
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_recommendation_training_jobs_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'SKIPPED_LOW_DATASET'))
);

CREATE INDEX idx_recommendation_training_jobs_status ON recommendation_training_jobs(status);
CREATE INDEX idx_recommendation_training_jobs_dataset ON recommendation_training_jobs(dataset_id);
CREATE INDEX idx_recommendation_training_jobs_created_at ON recommendation_training_jobs(created_at);
