-- P0: 사용자-관리자 상담방(support chat)을 AS AI Chat(as_chat_*)에서 완전히 분리한다.
-- V93은 as_chat_* 테이블에 상담용 컬럼/role/백필을 얹었으나, 그 방식은 3번(AS AI Chat) owner
-- 테이블과 4번(상담방) owner 데이터가 같은 테이블/제약/role enum을 공유하게 만들었다.
-- 이 마이그레이션은 (1) 상담방 전용 테이블을 신설하고, (2) V93이 as_chat_*에 남긴 흔적을
-- support_chat_*로 이전한 뒤, (3) as_chat_*를 AS AI Chat 전용 상태로 원복한다.

-- 1) 상담방 전용 테이블
CREATE TABLE support_chat_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  as_ticket_id BIGINT NOT NULL REFERENCES as_tickets(id),
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  title VARCHAR(160) NOT NULL DEFAULT 'AS 상담방',
  last_message_preview VARCHAR(240),
  last_message_at TIMESTAMPTZ,
  user_unread_count INTEGER NOT NULL DEFAULT 0,
  admin_unread_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_support_chat_rooms_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE UNIQUE INDEX ux_support_chat_rooms_active_ticket_user
  ON support_chat_rooms(user_id, as_ticket_id)
  WHERE status = 'ACTIVE' AND deleted_at IS NULL;

CREATE INDEX idx_support_chat_rooms_user_id ON support_chat_rooms(user_id);
CREATE INDEX idx_support_chat_rooms_as_ticket_id ON support_chat_rooms(as_ticket_id);
CREATE INDEX idx_support_chat_rooms_last_message_at ON support_chat_rooms(last_message_at);
CREATE INDEX idx_support_chat_rooms_deleted_at ON support_chat_rooms(deleted_at);

CREATE TABLE support_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  room_id BIGINT NOT NULL REFERENCES support_chat_rooms(id),
  role VARCHAR(30) NOT NULL,
  content TEXT NOT NULL,
  sender_user_id BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_support_chat_messages_role CHECK (role IN ('USER', 'ADMIN', 'SYSTEM'))
);

CREATE INDEX idx_support_chat_messages_room_id ON support_chat_messages(room_id);
CREATE INDEX idx_support_chat_messages_sender_user_id ON support_chat_messages(sender_user_id);
CREATE INDEX idx_support_chat_messages_created_at ON support_chat_messages(created_at);

-- 2) V93이 as_chat_*에 만든 상담방 흔적을 support_chat_*로 이전한다.
--    V93은 title='AS 상담방'인 세션을 상담방으로 백필했으므로 그 기준으로 식별한다.
--    상담용 컬럼(last_message_*, unread_*)이 V93에서 as_chat_sessions에 추가된 상태를 전제로 이전한다.
INSERT INTO support_chat_rooms (
  user_id,
  as_ticket_id,
  status,
  title,
  last_message_preview,
  last_message_at,
  user_unread_count,
  admin_unread_count,
  created_at,
  updated_at,
  deleted_at
)
SELECT s.user_id,
       s.as_ticket_id,
       s.status,
       s.title,
       s.last_message_preview,
       s.last_message_at,
       COALESCE(s.user_unread_count, 0),
       COALESCE(s.admin_unread_count, 0),
       s.created_at,
       COALESCE(s.updated_at, s.created_at),
       s.deleted_at
FROM as_chat_sessions s
WHERE s.title = 'AS 상담방';

-- 이전한 세션의 메시지를 support_chat_messages로 옮긴다.
-- 상담방 메시지는 role USER/ADMIN/SYSTEM만 가진다(V93이 만든 세션엔 ASSISTANT가 없다).
INSERT INTO support_chat_messages (
  room_id,
  role,
  content,
  sender_user_id,
  created_at
)
SELECT r.id,
       m.role,
       m.content,
       m.sender_user_id,
       m.created_at
FROM as_chat_messages m
JOIN as_chat_sessions s ON s.id = m.chat_session_id
JOIN support_chat_rooms r
  ON r.as_ticket_id = s.as_ticket_id
 AND r.user_id = s.user_id
 AND r.created_at = s.created_at
WHERE s.title = 'AS 상담방'
  AND m.role IN ('USER', 'ADMIN', 'SYSTEM');

-- 3) as_chat_*를 AS AI Chat 전용으로 원복한다.
--    3-1) V93이 백필한 상담방 세션(과 그 SYSTEM 메시지)을 as_chat_*에서 제거한다.
DELETE FROM as_chat_messages m
USING as_chat_sessions s
WHERE m.chat_session_id = s.id
  AND s.title = 'AS 상담방';

DELETE FROM as_chat_sessions
WHERE title = 'AS 상담방';

--    3-2) as_chat_messages role enum을 AS AI Chat 원래 도메인(USER/ASSISTANT)으로 되돌린다.
ALTER TABLE as_chat_messages
  DROP CONSTRAINT IF EXISTS chk_as_chat_messages_role;

ALTER TABLE as_chat_messages
  ADD CONSTRAINT chk_as_chat_messages_role
  CHECK (role IN ('USER', 'ASSISTANT'));

--    3-3) V93이 as_chat_*에 얹은 상담 전용 컬럼/인덱스를 제거한다(AS AI Chat은 사용하지 않는다).
DROP INDEX IF EXISTS idx_as_chat_sessions_last_message_at;
DROP INDEX IF EXISTS idx_as_chat_messages_sender_user_id;

ALTER TABLE as_chat_messages
  DROP COLUMN IF EXISTS sender_user_id;

ALTER TABLE as_chat_sessions
  DROP COLUMN IF EXISTS last_message_preview,
  DROP COLUMN IF EXISTS last_message_at,
  DROP COLUMN IF EXISTS user_unread_count,
  DROP COLUMN IF EXISTS admin_unread_count;
