-- ACTIVE 메인보드의 메모리(DIMM) 슬롯 수 백필.
-- 값은 제조사 공식 스펙 페이지 웹 검증(2026-07-06, 60/60 확인)으로 확정했다.
-- 이후 제조사 인테이크로 유입되는 보드는 memorySlots가 없을 수 있으며, 그 경우 램 슬롯 초과 검사는 생략된다.

UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock B850 Pro-A WiFi 디앤디컴 (AMD 소켓 AM5 메인보드) DDR5';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock B850 Pro-A 대원씨티에스 (AMD 소켓 AM5 메인보드) DDR5';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock B850 Pro-A 디앤디컴 (AMD 소켓 AM5 메인보드) DDR5';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock B850M Steel Legend WiFi';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock B860 Rock WiFi 7 에즈윈';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock B860M Pro RS WiFi';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '2'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock B860M Rock WiFi 디앤디컴';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '2'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock B860M Rock WiFi 디앤디컴 인텔 메인보드';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock X870E Nova WiFi 대원씨티에스';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock X870E Nova WiFi 디앤디컴';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock X870E Nova WiFi 디앤디컴 (AMD 소켓AM5 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock Z890 Pro RS WiFi 디앤디컴';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock Z890 Pro RS WiFi 디앤디컴 인텔 메인보드';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASRock Z890 Taichi 디앤디컴';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS B850M MAX GAMING WIFI 라이젠 AM5 게이밍 메인보드';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS PRIME B860-PLUS-CSM 코잇 (인텔 소켓1851메인보드) DDR5';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS PRIME B860M-A-CSM  코잇';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS PRIME X870-P WIFI-CSM 대원씨티에스 (AMD 소켓AM5 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS PRIME X870-P-CSM 대원씨티에스 (AMD 소켓AM5 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS ROG CROSSHAIR X870E HERO 인텍앤컴퍼니';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '2'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS ROG STRIX X870-I GAMING WIFI';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '2'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS ROG STRIX X870-I GAMING WIFI STCOM (AMD 소켓AM5 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS ROG STRIX X870E-A GAMING WIFI7 NEO 대원씨티에스';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS ROG STRIX X870E-E GAMING WIFI7 NEO 대원씨티에스';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '2'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS ROG STRIX Z890-I GAMING WIFI';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS TUF B850M-PLUS WIFI7 W 화이트 라이젠 AM5 게이밍 메인보드';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS TUF Gaming B850-PLUS WIFI 인텍앤컴퍼니';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'ASUS Z890 AYW GAMING WIFI W 코잇';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'GIGABYTE B850 AORUS ELITE WIFI7 ICE 제이씨현';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'GIGABYTE B850M AORUS ELITE WIFI6E';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'GIGABYTE B860 AORUS ELITE WIFI7 ICE 제이씨현';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'GIGABYTE B860M AORUS ELITE WIFI6E';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'GIGABYTE B860M AORUS ELITE WIFI6E ICE 제이씨현';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'GIGABYTE B860M AORUS ELITE WIFI6E ICE 피씨디렉트';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'GIGABYTE X870E AORUS PRO X3D ICE 제이씨현';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI B850 맥스 게임컴퓨터 조립용 시피유 라이젠메인보드 WIFI';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MAG B850M 박격포 WIFI MSI코리아';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MAG B860 토마호크 WIFI (인텔 소켓1851 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MAG B860M 박격포 WIFI';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MAG X870 토마호크 WIFI (AMD 소켓AM5 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MAG X870E 토마호크 WIFI';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MAG X870E 토마호크 WIFI (AMD 소켓AM5 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MPG B850 엣지 TI WIFI DDR5 AMD 메인보드';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '2'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MPG B850I EDGE TI WIFI';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MPG X870E 카본 WIFI (AMD 소켓AM5 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MPG Z890 카본 WIFI (인텔 소켓1851 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '2'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI MPG Z890I EDGE TI WIFI';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI PRO B860M-A WIFI (인텔 소켓1851 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI PRO Z890-A WIFI (인텔 소켓1851 DDR5 메인보드)';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '2'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = 'MSI Z890 유니파이-X 게임PC 조립용 메인보드 ATX';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = '기가바이트 B850M AORUS ELITE WIFI6E ICE 제이씨현';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = '기가바이트 B850M AORUS ELITE WIFI7 ICE-P 제이씨현';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = '기가바이트 X870 AORUS ELITE WIFI7 ICE  피씨디렉트';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = '기가바이트 X870 AORUS ELITE WIFI7 제이씨현 제이씨현';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = '기가바이트 X870E AORUS ELITE X3D 피씨디렉트, 화이트';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = '기가바이트 X870E AORUS PRO ICE 피씨디렉트';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = '기가바이트 Z890 AORUS ELITE WIFI7  제이씨현';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '4'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = '기가바이트 Z890 AORUS ELITE WIFI7 ICE  제이씨현';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '2'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = '기가바이트 Z890I AORUS ULTRA  제이씨현';
UPDATE parts SET attributes = jsonb_set(coalesce(attributes, '{}'::jsonb), '{memorySlots}', '2'::jsonb, true) WHERE category = 'MOTHERBOARD' AND name = '에이수스 ASUS B860M AYW GAMING WIFI 인텍앤컴퍼니 인텔 1851소켓 D5 메인보드';
